name: power-forecast
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=2.0.2
  - pandas=2.2.3
  - scikit-learn=1.6.1
  - scipy=1.13.1
  - matplotlib=3.9.4
  - seaborn=0.13.2
  - jupyterlab=4.3.4
  - ipykernel=6.29.5
  - xgboost=2.1.4
  - lightgbm=4.6.0
  - numba=0.60.0
  - numexpr=2.10.1
  - pip
  - pip:
      - tensorflow==2.19.0
      - keras==3.9.2
      - catboost==1.2.8
      - shap==0.47.2
      - plotly==6.1.1
      - tensorflow-io-gcs-filesystem==0.31.0
      - nbstripout
      - jupytext
